version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx_test
        ports:
            - "9889:80"
        volumes:
          #- ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
